# Generated by Django 5.0.7 on 2024-08-18 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_servings_timeoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cook_time', to='recipe.timeoption'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prep_time', to='recipe.timeoption'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='recipe.servings'),
        ),
    ]
