# Generated by Django 5.0.7 on 2024-08-17 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_recipe_cook_recipe_prep_recipe_servings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='recipe.servings'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cook_time', to='recipe.timeoption'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prep_time', to='recipe.timeoption'),
        ),
    ]
