# Generated by Django 5.0.7 on 2024-08-17 17:59

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_servings_timeoption_alter_recipe_servings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoption',
            name='value',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
