# Generated by Django 5.0.7 on 2024-08-21 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipe_cook_recipe_prep_recipe_servings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servings',
            old_name='size',
            new_name='serving',
        ),
        migrations.RenameField(
            model_name='timeoption',
            old_name='value',
            new_name='time',
        ),
    ]
