# Generated by Django 5.0.7 on 2024-08-17 18:20

from django.db import migrations

def fix_invalid_foreign_keys(apps, schema_editor):
    Recipe = apps.get_model('recipe', 'Recipe')
    Recipe.objects.filter(prep__value='unknown').update(prep=None)
    Recipe.objects.filter(cook__value='unknown').update(cook=None)
    Recipe.objects.filter(servings__value='unknown').update(servings=None)

class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_alter_timeoption_value'),
    ]

    operations = [
        migrations.RunPython(fix_invalid_foreign_keys),
    ]
