# Generated by Django 5.0.7 on 2024-09-12 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_alter_recipe_category_alter_recipe_cook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servings',
            old_name='serving',
            new_name='servings',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='recipe.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_servings', to='recipe.servings'),
        ),
    ]
