# Generated by Django 5.0.7 on 2024-09-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_rename_serving_servings_servings_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servings',
            new_name='Serving',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='servings',
            new_name='serving',
        ),
        migrations.RenameField(
            model_name='serving',
            old_name='servings',
            new_name='serving',
        ),
    ]
